import { Emotion } from "./Emotion";

export const emotions: Record<string, Emotion> = {
  acceptance: {
    hue: 120,
    valence: 0.7,
    baseArousal: 0.3,
    type: 'hedonic',
    name: 'Acceptance',
  },
  joy: {
    hue: 60,
    valence: 0.9,
    baseArousal: 0.7,
    type: 'hedonic',
    name: 'Joy',
  },
  anger: {
    hue: 0,
    valence: -0.3,
    baseArousal: 0.9,
    type: 'hedonic',
    name: 'Anger',
  },
  anticipation: {
    hue: 30,
    valence: 0.6,
    baseArousal: 0.8,
    type: 'hedonic',
    name: 'Anticipation',
  },
  disgust: {
    hue: 300,
    valence: -0.8,
    baseArousal: 0.4,
    type: 'agonic',
    name: 'Disgust',
  },
  sadness: {
    hue: 240,
    valence: -0.9,
    baseArousal: 0.2,
    type: 'agonic',
    name: 'Sadness',
  },
  surprise: {
    hue: 210,
    valence: -0.1,
    baseArousal: 0.95,
    type: 'agonic',
    name: 'Surprise',
  },
  fear: {
    hue: 180,
    valence: -0.7,
    baseArousal: 0.9,
    type: 'agonic',
    name: 'Fear',
  },
  love: {
    hue: 90,
    valence: 0.9,
    baseArousal: 0.5,
    type: 'hedonic-secondary',
    name: 'Love',
  },
  pride: {
    hue: 30,
    valence: 0.7,
    baseArousal: 0.8,
    type: 'hedonic-secondary',
    name: 'Pride',
  },
  curiosity: {
    hue: 165,
    valence: 0.5,
    baseArousal: 0.7,
    type: 'cross-secondary',
    name: 'Curiosity',
  },
  misery: {
    hue: 270,
    valence: -0.95,
    baseArousal: 0.3,
    type: 'agonic-secondary',
    name: 'Misery',
  },
  embarrassment: {
    hue: 210,
    valence: -0.8,
    baseArousal: 0.6,
    type: 'agonic-secondary',
    name: 'Embarrassment',
  },
  cynicism: {
    hue: 315,
    valence: -0.6,
    baseArousal: 0.5,
    type: 'cross-secondary',
    name: 'Cynicism',
  },
};
